apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
  namespace: alpha
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: slow
  resources:
    requests:
      storage: 1Gi