apiVersion: v1
kind: Pod
metadata:
  name: my-custom-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-scheduler
    - --master=http://127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf

    image: gcr.io/google_containers/kube-scheduler-amd64:v1.11.3
    name: kube-scheduler
