apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-03-01T23:37:15Z"
  labels:
    name: webapp-color
  name: webapp-color
  namespace: default
  resourceVersion: "902"
  uid: e02f4e28-9fa4-4a6e-8d35-46b99d45a166
spec:
  containers:
    - env:
        - name: APP_COLOR
          value: pink
      image: kodekloud/webapp-color
      imagePullPolicy: Always
      name: webapp-color
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-4wq6t
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: controlplane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: kube-api-access-4wq6t
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: "2023-03-01T23:37:15Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2023-03-01T23:37:21Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2023-03-01T23:37:21Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2023-03-01T23:37:15Z"
      status: "True"
      type: PodScheduled
  containerStatuses:
    - containerID: containerd://0df8e232bea7d42b650728d2004a828ecb2bd3067de8e97bb0686d5b8bae2de4
      image: docker.io/kodekloud/webapp-color:latest
      imageID: docker.io/kodekloud/webapp-color@sha256:99c3821ea49b89c7a22d3eebab5c2e1ec651452e7675af243485034a72eb1423
      lastState: {}
      name: webapp-color
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2023-03-01T23:37:20Z"
  hostIP: 172.25.0.15
  phase: Running
  podIP: 10.42.0.9
  podIPs:
    - ip: 10.42.0.9
  qosClass: BestEffort
  startTime: "2023-03-01T23:37:15Z"
