apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storage-admin
rules:
- apiGroups:
  - '*'
  resources:
  - 'persistentvolumes'
  - 'storageclasses'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'